<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-05-07 08:36
=======
# Generated by Django 4.0.4 on 2022-05-07 10:02
>>>>>>> 267072fab092eb3a8d711aa7c4dc622ec98dcee8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_examtimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='exam.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='exam.exam'),
        ),
    ]
