# Generated by Django 4.0.1 on 2022-02-19 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='username',
            field=models.ForeignKey(default='sultan', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
