# Generated by Django 4.0.1 on 2022-02-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_user', '0002_about_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='username',
        ),
    ]
