# Generated by Django 4.0 on 2022-03-11 14:47

from django.db import migrations, models
import students_base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название урока')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to=students_base.models.image_save_path, verbose_name='Изображение')),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Уроки',
                'ordering': ['id'],
            },
        ),
    ]
